# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# HTML Title
title: "Rockbros Links"

# Avatar image path
avatar: "https://tc.113119.xyz/file/AgACAgIAAyEGAAS8BEVcAAMNaWSuK4ePsdTcDDKV2eeZV_1XNyQAAngOaxtWNiFLZAw-KJbrIYkBAAMCAAN5AAM4BA.jpg"

# Name section text
name: "@ROCKBROS"

# Tagline section text
tagline: >-
    Rockbros Official Store: Premium Cycling Gear for Every Adventure.

# 连结列表  
# icon：使用 Font Awesome 图示 (https://fontawesome.com/search?o=r&m=free)  
# text：显示在连结上的文字  
# title：连结的标题  
# url：连结的网址  
# alt：替代文字（无障碍使用）  
# target：`_blank` 在新页签打开，`_self` 在同页面打开  
links:
  - link:
      icon: "fa-brands fa-medium"
      text: "CLOTHING <span class='link-button-text'>(100+ Posts)</span>"
      url: "https://rockbrosclothing.com/collections/clothing"
      alt: "Rockbros Tech Blog"
      title: "Rockbros Tech Blog"
      target: "_blank"

# 社交媒体连结列表  
# icon：使用 Font Awesome 图示 (https://fontawesome.com/search?o=r&m=free)  
# title：连结的标题  
# url：社交媒体连结的网址  
# alt：替代文字（无障碍使用）  
# target：`_blank` 在新页签打开，`_self` 在同页面打开 
socials:
  - social:
      icon: "fa-brands fa-facebook"
      url: "https://www.facebook.com/profile.php?id=61586196594209"
      title: "Facebook"
      alt: "Rockbros Facebook"
      target: "_blank"
  - social:
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/rockbros_clothing/"
      title: "Instagram"
      alt: "Rockbros Instagram"
      target: "_blank"
  - social:
      icon: "fa-solid fa-envelope"
      url: "mailto:service@rockbrosclothing.com"
      title: "Email: service@rockbrosclothing.com"
      alt: "service@rockbrosclothing.com"
      target: "_blank"

# Footer text
footer: >
    Welcome to Rockbros! Follow us on Facebook or Instagram to stay connected.

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2010-2026  <a href="https://rockbrosclothing.com/" target="_blank">Rockbros</a>.
