# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# HTML Title
title: "ZhgChgLi's Links"

# Avatar image path
avatar: "./images/profile.jpeg"

# Name section text
name: "@ROCKBROS"

# Tagline section text
tagline: >-
    ROCKBROS Official Store: Premium Cycling Gear for Every Adventure.

# 连结列表  
# icon：使用 Font Awesome 图示 (https://fontawesome.com/search?o=r&m=free)  
# text：显示在连结上的文字  
# title：连结的标题  
# url：连结的网址  
# alt：替代文字（无障碍使用）  
# target：`_blank` 在新页签打开，`_self` 在同页面打开  
links:
  - link:
      icon: "fa-brands fa-medium"
      text: "Tech Blog <span class='link-button-text'>(100+ Posts)</span>"
      url: "https://blog.zhgchg.li"
      alt: "ZhgChgLi's Tech Blog"
      title: "ZhgChgLi's Tech Blog"
      target: "_blank"
  - link:
      icon: "fa-brands fa-medium"
      text: "Travelog <span class='link-button-text'>(10+ Posts)</span>"
      url: "https://medium.com/ztravel"
      alt: "ZhgChgLi's Travelog"
      title: "ZhgChgLi's Travelog"
      target: "_blank"
  - link:
      icon: "fa-solid fa-rss"
      text: "Website"
      url: "https://zhgchg.li/"
      alt: "ZhgChgLi's Website"
      title: "ZhgChgLi's Website"
      target: "_blank"
  - link:
      icon: "fa-brands fa-swift"
      text: "ZMarkupParser <span class='link-button-text'>({{vars.GithubRepoStarsCountPlugin['ZhgChgLi/ZMarkupParser']}} Stars)</span>"
      url: "https://github.com/ZhgChgLi/ZMarkupParser"
      alt: "ZMarkupParser is a pure-Swift library that helps you to convert HTML strings to NSAttributedString with customized style and tags."
      title: "ZMarkupParser is a pure-Swift library that helps you to convert HTML strings to NSAttributedString with customized style and tags."
      target: "_blank"
  - link:
      icon: "fa-brands fa-app-store-ios"
      text: "ZReviewTender <span class='link-button-text'>({{vars.GithubRepoStarsCountPlugin['ZhgChgLi/ZReviewTender']}} Stars)</span>"
      url: "https://github.com/ZhgChgLi/ZReviewTender"
      alt: "ZReviewTender is a tool for fetching app reviews from the App Store and Google Play Console and integrating them into your workflow."
      title: "ZReviewTender is a tool for fetching app reviews from the App Store and Google Play Console and integrating them into your workflow."
      target: "_blank"
  - link:
      icon: "fa-brands fa-markdown"
      text: "ZMediumToMarkdown <span class='link-button-text'>({{vars.GithubRepoStarsCountPlugin['ZhgChgLi/ZMediumToMarkdown']}} Stars)</span>"
      url: "https://github.com/ZhgChgLi/ZMediumToMarkdown"
      alt: "ZMediumToMarkdown is a powerful tool that allows you to effortlessly download and convert your Medium posts to Markdown format."
      title: "ZMediumToMarkdown is a powerful tool that allows you to effortlessly download and convert your Medium posts to Markdown format."
      target: "_blank"
  - link:
      icon: "fa-brands fa-github"
      text: "linkyee <span class='link-button-text'>({{vars.GithubRepoStarsCountPlugin['ZhgChgLi/linkyee']}} Stars)</span>"
      url: "https://github.com/ZhgChgLi/linkyee"
      alt: "linkyee is a fully customized, open-source LinkTree alternative deployed directly on GitHub Pages."
      title: "linkyee is a fully customized, open-source LinkTree alternative deployed directly on GitHub Pages."
      target: "_blank"


# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-facebook"
      url: "https://www.facebook.com/profile.php?id=61586196594209"
      title: "FaceBook"
      alt: "Rockbros FaceBook"
      target: "_blank"
  - social:
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/rockbros_clothing/"
      title: "Instagram"
      alt: "Rockbros Instagram"
      target: "_blank"
  - social:
      icon: "fa-solid fa-envelope"
      url: "mailto:service@rockbrosclothing.com"
      title: "Email: service@rockbrosclothing.com"
      alt: "service@rockbrosclothing.com"
      target: "_blank"

# Footer text
footer: >
    Welcome to Rockbros! Follow us on Facebook or Instagram to stay connected.

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2010-2026  <a href="https://rockbrosclothing.com/" target="_blank">Rockbros</a>.
